server:
  port: 8002
spring:
  application:
    name: account
  datasource:
    username: application
    password: 19960118
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://1.15.157.125:3306/test_demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC

eureka:
  client:
    service-url:
      defaultZone: http://center.com:7900/eureka/
